services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./app/:/var/www/html/
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mysqldb