services:
  php:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - main-volume:/var/www/html/
      - ./app/:/var/www/html/
    networks:
      - main-network

volumes:
  main-volume:
    external: true
  mysql-volume:
    external: true

networks:
  main-network:
    external: true